### ISSUE TITLE
Rewrite community.ciscosmb.ciscosmb_facts to community.ciscosmb.facts

### ISSUE THREAD

**Issue by qaxi** [ansible-collections/community.ciscosmb#29]
##### SUMMARY

Rewrite community.ciscosmb.ciscosmb_facts to community.ciscosmb.facts
and Rewrite community.ciscosmb.ciscosmb_command to community.ciscosmb.command
##### ISSUE TYPE
- community.ciscosmb.ciscosmb_facts is duplicating name ciscosmb

##### COMPONENT NAME

* modules ciscosmb_command and ciscosmb_facts
* 
##### ADDITIONAL INFORMATION

```yaml
tasks:
    - name: CiscoSMB - Gather Facts - subset default
      # communtity.ciscosmb.ciscosmb_facts:
      communtity.ciscosmb.facts:
        gather_subset:
          - default
```
