### ISSUE TITLE
How to pass STDIN to commands

### ISSUE THREAD

**Issue by FooBarTrixibell** [ansible-collections/community.ciscosmb#59]
##### SUMMARY

Possibly just an addition to documentation, I need to know how to pass STDIN to the module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Documentation -
Add documentation on how to pass things to STDIN (ie. when the command 'crypto certificate 2 import' is called it wants a certificate to be passed and a . on a new line).

##### ADDITIONAL INFORMATION

I believe there are multiple commands in the SMB CIOS which require this.

Note: arg: with stdin does NOT work.

```yaml
 tasks:
        - name: set certificate 2
          community.ciscosmb.command:
            commands: 
             - conf
             - crypto certificate 2 import
            args:
                stdin: "-----BEGIN RSA PRIVATE KEY-----
-----END CERTIFICATE-----
.
"
```

**Comment by FooBarTrixibell** [comment]
I found a gist here - https://gist.github.com/h3po/8c82e9ee86ba8c12cb71d717b29a9d56

and modified it to be a bit simpler (just to use a pre-created cert in the right format) -
```
- name: Set the SSL Certificate
  gather_facts: no
  hosts: all
  vars:
    certpath: "files/SwitchCert.crt"

  tasks:
    - name: read certificate into variable
      set_fact:
        cert: "{{ lookup('file', certpath) }}"

    - name: upload the certificate and keys
      community.ciscosmb.command:
        commands:
          - config
          - "crypto certificate 2 import\n{{ cert }}\n."
      register: tmp
      failed_when: "'Certificate imported successfully' not in tmp.stdout[1]"
      
    - name: enable the certificate
      community.ciscosmb.command:
        commands:
          - ip https certificate 2
```
I guess the important bit (I like to think I may have worked it out from this) is the command in quotes with escaped newline characters.

I think perhaps a few more usage example might be handy too, just to highlight just how easy it is to configure switches with this plugin.

Thanks for this module by the way, it is awesome.
