### ISSUE TITLE
CBS350-24T-4G: "Failed to authenticate: Authentication failed."

### ISSUE THREAD

**Issue by deflago** [ansible-collections/community.ciscosmb#64]
##### SUMMARY

I have a "CBS350-24T-4G" which I'm trying to automate with Ansible. Authentication via ssh on the terminal works as expected, with password and with ssh-key. Trying to authenticate with ansible results in the error seen in the title.
My inventory looks like this:
```yaml
all:
  children:
    network:
      hosts:
        cbs350.example.com:
          ansible_host: 192.168.1.1
          ansible_network_os: community.ciscosmb.ciscosmb
          ansible_connection: ansible.netcommon.network_cli
#          ansible_ssh_private_key_file: /home/user/.ssh/id_rsa
#          ansible_ssh_pass: **password**
          ansible_become_method: enable
          ansible_become_password: **password**
          ansible_become: true
          ansible_network_cli_ssh_type: paramiko
```

The playbook looks like this:
```yaml
- gather_facts: no
  hosts: cbs350.example.com
  remote_user: "user"
  tasks:
    - name: "Create login banner"
      community.ciscosmb.command:
        commands: 
          - "banner login $"
          - "###############################"
          - "#  Authorized personal only!  #"
          - "###############################"
          - "$"
```
The log on the switch shows the following:
```
11-Nov-2022 17:10:56 :%AAA-W-REJECT: New ssh connection, source 192.168.1.100 destination 192.168.1.1  REJECTED
11-Nov-2022 17:10:56 :%AAA-W-REJECT: New ssh connection, source 192.168.1.100 destination 192.168.1.1  REJECTED
11-Nov-2022 17:10:56 :%AAA-W-REJECT: New ssh connection, source 192.168.1.100 destination 192.168.1.1  REJECTED

```
The debug logging on the switch doesn't yield any other information than this.

What is my issue here? 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.ciscosmb.command

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION

```paste below
community.ciscosmb            1.0.5
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/home/user/Dokumente/Projects/ansible.cfg) = ['timer']
DEFAULT_HOST_LIST(/home/user/Dokumente/Projects/ansible.cfg) = ['/media/nfs/user/Projects/Ansible/Projects/inventory.yml']
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_LOG_PATH(/home/user/Dokumente/Projects/ansible.cfg) = /media/nfs/user/Projects/Ansible/Projects/log/ansible.log
DEFAULT_ROLES_PATH(/home/user/Dokumente/Projects/ansible.cfg) = ['/media/nfs/user/Projects/Ansible/Projects/roles']

```

##### OS / ENVIRONMENT

Device: CBS350-24T-4G 
Version: 3.0.0.69

##### STEPS TO REPRODUCE

see above

##### EXPECTED RESULTS

Successful connect

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_community.ciscosmb.command_payload_qty2t7_4/ansible_community.ciscosmb.command_payload.zip/ansible_collections/community/ciscosmb/plugins/module_utils/ciscosmb.py", line 219, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_community.ciscosmb.command_payload_qty2t7_4/ansible_community.ciscosmb.command_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [cbs350.example.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "banner login $",
                "###############################",
                "#  Authorized personal only!  #",
                "###############################",
                "$"
            ],
            "interval": 1,
            "match": "all",
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "Failed to authenticate: Authentication failed."
}

```
