### ISSUE TITLE
Add support for netcommon/gather_facts

### ISSUE THREAD

**Issue by gaby** [ansible-collections/community.ciscosmb#68]
Currently all the examples use this:

```yaml
- name: Gather Facts
  gather_facts: no
  hosts: all
```

And require using the custom facts task from the collection. All the other main cisco platforms support netcommon. With the SMB collection if you do `gather_facts: yes` it grabs the facts from the host running the playbooks not the facts from the Cisco device. This is very confusing, is there a way to use `gather_facts: yes` with Cisco SMB?
