### ISSUE TITLE
bandwith not bandwidth

### ISSUE THREAD

**Issue by jscooksey** [ansible-collections/community.ciscosmb#71]
##### SUMMARY
the [facts module](https://github.com/ansible-collections/community.ciscosmb/blob/main/plugins/modules/facts.py) seems to reference interface bandwidth as **bandwith**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
/plugins/modules/facts.py

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.2]
  config file = /home/newera/ansible/ansible.cfg
  configured module search path = ['/home/newera/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/newera/.local/pipx/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/newera/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/newera/.local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/newera/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
community.ciscosmb 1.0.6 
```

**NB can see in current 1.0.7 code on GitHub**

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/newera/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/newera/ansible/ansible.cfg) = ['/home/newera/ansible/inventory/netbox.yml']
HOST_KEY_CHECKING(/home/newera/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 22.04.2 LTS

##### STEPS TO REPRODUCE

```yaml
- name: Get Raw JSON to examine on Interfaces
  hosts: device_roles_switch
  connection: local
  gather_facts: no
  vars:
    ansible_network_os: community.ciscosmb.ciscosmb

  tasks:
    - name: Collect Interfaces
      community.ciscosmb.facts:
        gather_subset:
          - interfaces

    - name: Debug Output
      debug:
        msg: "{{ ansible_facts }}"
```

##### EXPECTED RESULTS

Expected the term to be **bandwidth** with the *d* in it

##### ACTUAL RESULTS

```paste below
    "net_interfaces": {
        "GigabitEthernet1/0/1": {
            "admin_state": "up",
            "bandwith": null,
            "control": null,
            "description": "9  PCs",
            "duplex": null,
            "mdix": "auto",
            "mode": null,
            "mtu": 1518,
            "negotiation": null,
            "presure": null,
            "state": "down",
            "type": "1G-Copper"
        },
```
