### ISSUE TITLE
ssh_common_args not being applied to ssh connection

### ISSUE THREAD

**Issue by ckhordiasma** [ansible-collections/community.ciscosmb#77]
##### SUMMARY

Hello, I am running into an issue on my SG300 switch. This switch has outdated algorithms for key exchange and others, so i have to set ssh config parameters to non-default values in order to connect to it. 

I wanted to be able to specify key exchange algorithms as host/inventory variables, but it does not seem to be applying my ssh_common_args settings when I try to run ansible playbooks. My workaround is to have the appropriate configuration in my ~/.ssh/config file, which works as expected. I am not sure if this is a problem with this specific module or if it is a general ansible problem.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.4]
  config file = /home/chkodama/projects/lab-iac/ansible/ansible.cfg
  configured module search path = ['/home/chkodama/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/chkodama/projects/lab-iac/ansible/venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/chkodama/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/chkodama/projects/lab-iac/ansible/venv/bin/ansible
  python version = 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] (/home/chkodama/projects/lab-iac/ansible/venv/bin/python3.12)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

Collection         Version
------------------ -------
community.ciscosmb 1.0.9  

Collection         Version
------------------ -------
community.ciscosmb 1.0.7  
```

##### OS / ENVIRONMENT

arch linux connecting to Cisco SG-300

##### STEPS TO REPRODUCE

Attempt to run any playbook on a switch using the following host variables (and ~/.ssh/config unset for the switch ip)

```yaml
ansible_network_os: community.ciscosmb.ciscosmb
ansible_become_method: enable
ansible_ssh_port: 22
# ansible_host_key_checking: false

# had better error message with libssh versus paramiko
ansible_network_cli_ssh_type: libssh
# ansible_network_cli_ssh_type: paramiko

ansible_connection: network_cli


# neither of these worked

# ansible_ssh_common_args: "-F config/switch1-ssh-config"
ansible_ssh_common_args: >-
  -o KexAlgorithms diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1 
  -o MACs hmac-sha1   
  -o HostKeyAlgorithms ssh-rsa 
  -o PubkeyAcceptedKeyTypes ssh-rsa

```

workaround: add the following config to ~/.ssh/config:

```
Host <IP-ADDR-HERE>
  KexAlgorithms diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1
  MACs hmac-sha1
  HostKeyAlgorithms ssh-rsa
  PubkeyAcceptedKeyTypes ssh-rsa
```

##### EXPECTED RESULTS

playbook to run correctly

### error with libssh

```
fatal: [switch1]: FAILED! => {"changed": false, "msg": "
ssh connection failed: ssh connect failed: kex error : no match for method kex algos: 
server [diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1], 
client [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,
ecdh-sha2-nistp521,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,
diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256]"}
```

### error with paramiko

```
The full traceback is:
  File "/tmp/ansible_community.ciscosmb.command_payload_9n59q7ms/ansible_community.ciscosmb.command_payload.zip/ansible_collections/community/ciscosmb/plugins/module_utils/ciscosmb.py", line 290, in run_commands
    out = connection.get(command, prompt, answer)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_community.ciscosmb.command_payload_9n59q7ms/ansible_community.ciscosmb.command_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [switch1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "disable"
            ],
            "interval": 1,
            "match": "all",
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "Failed to authenticate: Authentication failed."
}
```
